#!/bin/bash -eux
APP=Citra
LOWERAPP=${APP,,}
INSTALLDIRLOC=/$APP/$APP.AppDir

export LD_LIBRARY_PATH=${INSTALLDIRLOC}/usr/lib:$LD_LIBRARY_PATH
export CC="clang-3.9 -stdlib=libc++" 
export CXX="clang++-3.9 -stdlib=libc++"
git clone --recursive https://github.com/citra-emu/citra.git
mkdir -p ${INSTALLDIRLOC}/usr/bin
cd citra
mkdir build
cd build
cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=${INSTALLDIRLOC}/usr -DCMAKE_BUILD_TYPE=Release
ninja
ninja install